### ISSUE TITLE
Long section tool outdated.

### ISSUE THREAD

**Issue by GigaChadOneHunned** [TUFLOW-Support/PyTuflow#1]
Hello Chads,

The ResData.getLPConnectivity() function is outdated and doesn't match the version supplied in the QGIS plugin. The superseded version doesn't work properly for multiple paths when the downstream channel is specified because it does not implement ResData.LP_force_connection() as per the version supplied with QGIS. Would it be possible to have his repo updated?

It's useful to do this outside of QGIS to beautify the plots for reporting purposes, for example:

![image](https://github.com/TUFLOW-Support/PyTuflow/assets/151147833/33a77e49-2b4a-40dc-bfb7-744c1fc12b5b)

**Comment by TUFLOW-Support** [comment]
Hi GigaChadHunned, we've updated pytuflow so that the long profile method works even if the channels are not connected via the main path. It should be available to upgrade via pip.

Thanks for reminding us to update! If you're happy, please close the ticket.
